version: "3.8"
services:
  app:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
      - /mnt/c/Users:/mnt/windows
    stdin_open: true
    tty: true
